### ISSUE TITLE
Version prompt incorrect

### ISSUE THREAD

**Issue by aonoa** [bali-framework/bali-cli#52]
Version prompt incorrect
![image](https://github.com/bali-framework/bali-cli/assets/32682251/6cb71088-fe3a-496d-9183-1fee6f952720)

**Comment by JoshYuJump** [comment]
@aonoa Thanks for your fead back, I have pushed a commit (https://github.com/bali-framework/bali-cli/commit/4265e7b6af5ad5ab100cd7906d447eb7360f6c53) to fix it. It will released in `v1.7.1`.
